# Generated by Django 3.2.4 on 2021-06-08 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foiv', models.CharField(max_length=64, verbose_name='ФОИВ')),
                ('Document_type', models.CharField(max_length=64, verbose_name='Тип документа')),
                ('Document_number', models.CharField(max_length=64, verbose_name='Номер документа')),
                ('Document_init_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания документа')),
                ('Stage_name', models.IntegerField(choices=[(1, 'Аннулирование'), (2, 'Внесение остатка/выдача перерасхода'), (3, 'Выгрузка'), (4, 'Отражение в учете'), (5, 'Регистрация в учете'), (6, 'Согласование'), (7, 'Установка статуса выгрузки'), (8, 'Утверждение'), (9, 'Формирование'), (10, 'Формирование и выгрузка'), (11, 'Формирование отправки')], verbose_name='Этап')),
                ('Stage_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проведения этапа')),
                ('Stage_user', models.CharField(max_length=64, verbose_name='Исполнитель')),
                ('Is_aborted', models.BooleanField(default=False, verbose_name='Прервана')),
                ('Is_done', models.BooleanField(default=True, verbose_name='Выполнена')),
                ('Marked_on_delete', models.BooleanField(default=False, verbose_name='Пометка на удаление')),
            ],
        ),
    ]
